name: Build Butane configurations

on:
  workflow_call:
    inputs:
      basedir:
        description: Base directory that contains all local files, including the main Butane file.
        required: true
        type: string
      bu:
        description: Name of the input Butane file, sans extension.
        required: true
        type: string
      ign:
        description: Name of the output Ignition file, sans extension.
        required: true
        type: string

jobs:
  main:
    name: Build Butane configurations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the main Butane file
        run: |
          docker pull quay.io/coreos/butane:release
          docker run \
            --interactive \
            --rm \
            --security-opt label=disable \
            --volume ${{ github.workspace }}:/pwd \
            --workdir /pwd \
            quay.io/coreos/butane:release \
            --pretty \
            --strict \
            --files-dir ${{ inputs.basedir }} \
            < ${{ inputs.basedir }}/${{ inputs.bu }}.bu \
            > ${{ inputs.ign }}.ign

      - name: Upload the produced Ignition file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: butane-${{ inputs.name }}
          path: ${{ inputs.ign }}.ign
