name: Build Butane configurations

on:
  workflow_call:
    inputs:
      path:
        description: Path to the main Butane file.
        required: true
        type: string
      name:
        description: Name of the produced Ignition file wihtout the extension.
        required: true
        type: string

jobs:
  main:
    name: Build Butane configurations
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the main Butane file
        run: |
          docker pull quay.io/coreos/butane:release
          docker run \
            --interactive \
            --rm \
            --security-opt label=disable \
            --volume ${{ github.workspace }}:/pwd \
            --workdir /pwd \
            quay.io/coreos/butane:release \
            --pretty \
            --strict \
            < ${{ inputs.path }}
            > ${{ inputs.name }}.ign

      - name: Upload the produced Ignition file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: butane-${{ inputs.name }}
          path: ${{ inputs.name }}.ign
