name: Update repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-coffeehouse:
    name: Build Butane configuration for Coffeehouse
    uses: ./.github/workflows/build-butane.yml
    with:
      basedir: coffeehouse
      bu: main
      ign: coffeehouse
    secrets: inherit

  build-millhouse:
    name: Build Butane configuration for Millhouse
    uses: ./.github/workflows/build-butane.yml
    with:
      basedir: millhouse
      bu: main
      ign: millhouse
    secrets: inherit

  build-roastery:
    name: Build Butane configuration for Roastery
    uses: ./.github/workflows/build-butane.yml
    with:
      basedir: roastery
      bu: main
      ign: roastery
    secrets: inherit

  deploy-pages:
    name: Deploy the artifacts to GitHub Pages
    if: github.ref == 'refs/heads/main'
    needs:
      - build-cafe-lounge
      - build-coffeehouse
      - build-millhouse
      - build-roastery
    uses: ./.github/workflows/deploy-pages.yml
    secrets: inherit
