name: Update flake

on:
  schedule:
    - cron: 0 0 * * 0 # every sunday at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  main:
    name: Update flake.lock
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Update flake.lock
        run: nix flake update

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore(flake): update flake.lock"
