name: Update repository

on: [push, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-butane:
    name: Build Butane configuration for Espresso
    uses: ./.github/workflows/build-butane.yml
    with:
      basedir: espresso
      bu: main
      ign: espresso
    secrets: inherit

  deploy-pages:
    name: Deploy the artifacts to GitHub Pages
    needs:
      - build-butane
    uses: ./.github/workflows/deploy-pages.yml
    secrets: inherit
