name: Update repository

on: [push, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-coffeehouse:
    name: Build Butane configuration for Coffeehouse
    uses: ./.github/workflows/build-butane.yml
    with:
      basedir: coffeehouse
      bu: main
      ign: coffeehouse
    secrets: inherit

  build-roastery:
    name: Build Butane configuration for Roastery
    uses: ./.github/workflows/build-butane.yml
    with:
      basedir: roastery
      bu: main
      ign: roastery
    secrets: inherit

  deploy-pages:
    name: Deploy the artifacts to GitHub Pages
    needs:
      - build-coffeehouse
      - build-roastery
    uses: ./.github/workflows/deploy-pages.yml
    secrets: inherit
